### PR TITLE
initial commit, added local development/server docs

### PR DESCRIPTION
**Pull request by aydanjiwanimetrist**
Added local setup in file, feel free to comment if there's anything I missed

### CODE REVIEW

**Comment by rduffield** [comment]
@aydanjiwanimetrist I believe the ticket is referring to how to set up a local development environment for this repository, such that a developer can run and view the product documentation locally.

**Comment by aydanjiwanimetrist** [comment]
@rduffield thanks, so should it follow these steps? https://dev.readthedocs.io/en/latest/install.html

**Comment by aydanjiwanimetrist** [comment]
Added the specific local docs setup, is the information on running locally still useful or should I remove that entirely?

**Comment by rduffield** [comment]
This repository gets published publicly at https://docs.metrist.io/en/latest/ so our other local dev stuff is not needed here.

**Comment by rduffield** [comment]
Looking good. The last things I recommend are moving this to `README.md` and removing the navigation item from the YAML.

**Pull request merged**
